/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CtlDataMining;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Johnny
 */
public class JfrmCargaDatos extends javax.swing.JFrame {

    /**
     * Creates new form JfrmCargaDatos
     */
    CtlDataMining controller;

    public JfrmCargaDatos() {
        initComponents();
        controller = new CtlDataMining();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpIndex = new javax.swing.JPanel();
        JbtnSeleccionarArchivo = new javax.swing.JButton();
        JbtnIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JlblRuta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtxtAFile = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JpIndex.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion de archivo"));
        JpIndex.setToolTipText("");

        JbtnSeleccionarArchivo.setText("Seleccionar archivo");
        JbtnSeleccionarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnSeleccionarArchivoActionPerformed(evt);
            }
        });

        JbtnIniciar.setText("Iniciar proceso");
        JbtnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnIniciarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Ruta:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Contenido archivo"));

        JtxtAFile.setColumns(20);
        JtxtAFile.setRows(5);
        jScrollPane1.setViewportView(JtxtAFile);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout JpIndexLayout = new javax.swing.GroupLayout(JpIndex);
        JpIndex.setLayout(JpIndexLayout);
        JpIndexLayout.setHorizontalGroup(
            JpIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpIndexLayout.createSequentialGroup()
                .addGroup(JpIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpIndexLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(JbtnSeleccionarArchivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JbtnIniciar)
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addGroup(JpIndexLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JpIndexLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JlblRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JpIndexLayout.setVerticalGroup(
            JpIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpIndexLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbtnSeleccionarArchivo)
                    .addComponent(JbtnIniciar))
                .addGap(28, 28, 28)
                .addGroup(JpIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JlblRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JpIndex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JpIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbtnSeleccionarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnSeleccionarArchivoActionPerformed
        //Ruta del archivo       
        String ruta;
        //se crea el FileChosser 
        final JFileChooser chooser = new JFileChooser();
        //Se definen los formatos soportados
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos arff", "arff");
        //Se le añaden los formatos al fileChooser
        chooser.setFileFilter(filter);
        //Se abre el file chooser, asignandolo como hijo al jpanel principal
        chooser.showOpenDialog(JpIndex);
        //Se captura la ruta del archivo seleccionado
        ruta = chooser.getSelectedFile().toString();
        //Se muestra la ruta en pantalla
        JlblRuta.setText(ruta);

        try {
            if (!ruta.equals("")) { //si se ha seleccionado archivo
                //Se lee el archivo
                BufferedReader file = new BufferedReader(new FileReader(ruta));
                //se le añade el contenido al objeto de tipo mensaje, convirtiendo el Buffer en un String
                JtxtAFile.setText(convertir(file));
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_JbtnSeleccionarArchivoActionPerformed

    private void JbtnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnIniciarActionPerformed
        String mensaje = JtxtAFile.getText();
        String res = controller.mineria(mensaje);

        JfrmResultado salida = new JfrmResultado(res);
        salida.setVisible(true);//solo se muestra la interfaz cuando se ha recibido el mensaje
    }//GEN-LAST:event_JbtnIniciarActionPerformed

    public String convertir(BufferedReader file) throws IOException {
        //Almacena la linea leida del file
        String temp;
        //cadena final
        String cadena = "";
        //Mienstras pueda leer una nueva linea del buffer
        while ((temp = file.readLine()) != null) {
            //Concatenelo
            cadena = cadena + temp + "\n";
        }
        return cadena;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmCargaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmCargaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmCargaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmCargaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmCargaDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnIniciar;
    private javax.swing.JButton JbtnSeleccionarArchivo;
    private javax.swing.JLabel JlblRuta;
    private javax.swing.JPanel JpIndex;
    private javax.swing.JTextArea JtxtAFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
